import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/footer";

const kurale = localFont({
  src: "./fonts/Kurale-Regular.ttf",
  variable: "--font-kurale",
  weight: "400",
});
const notoSans = localFont({
  src: "./fonts/Noto-Sans-regular.woff",
  variable: "--font-noto-sans",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kurale.variable} ${notoSans.variable} antialiased`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
